# config.py
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID")
DATASET_ID = os.getenv("DATASET_ID")
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

# Define a dictionary mapping artist names to their YouTube channel IDs
ARTIST_YOUTUBE_IDS = {
    "Justin Bieber": "UCIwFjwMjI0y7PDBVEO9-bkQ",
    "Taylor Swift": "UCqECaJ8Gagnn7YCbPEzWH6g",
    "Drake": "UCByOQJjav0CUDwxCk-jVNRQ",
    "Ed Sheeran": "UC0C-w0YjGpqDXGB8IHb662A",
    "Rihanna": "UCcgqSM4YEo5vVQpqwN-MaNw",
    "The Weeknd": "UC0WP5P-ufpRfjbNrmOWwLBQ",
    "Eminem": "UCfM3zsQsOnfWNUppiycmBuw",
    "Ariana Grande": "UC9CoOnJkIBMdeijd9qYoT_g",
    "Bruno Mars": "UCoUM-UJ7rirJYP8CQ0EIaHA",
    "Nicki Minaj": "UC3jOd7GUMhpgJRBhiLzuLsg",
    "Chris Brown": "UCcYrdFJF7hmPXRNaWdrko4w",
    "Katy Perry": "UCYvmuw-JtVrTZQ-7Y4kd63Q",
    "Jason Derulo": "UCe3yZzUwpmy2eKKmF9svX0Q",
    "Maroon 5": "UCBVjMGOIkavEAhyqpxJ73Dw",
    "David Guetta": "UC1l7wYrva1qCH-wgqcHaaRg",
    "Lady Gaga": "UCNL1ZadSjHpjm4q9j2sVtOA",
    "Selena Gomez": "UCPNxhDvTcytIdvwXWAm43cA",
    "Coldplay": "UCDPM_n1atn2ijUwHd0NNRQw",
    "Lil Wayne": "UCO9zJy7HWrIS3ojB4Lr7Yqw",
    "Imagine Dragons": "UCT9zcQNlyht7fRlcjmflRSA",
    "Sia": "UCN9HPn2fq-NL8M5_kp4RWZQ",
    "Billie Eilish": "UCiGm_E4ZwYSHV3bcW1pnSeQ",
    "Beyoncé": "UCuHzBCaKmtaLcRAOoazhCPA",
    "Michael Jackson": "UC5OrDvL9DscpcAstz7JnQGA",
    "Linkin Park": "UCZU9T1ceaOgwfLRq7OKFU4Q",
    "Wiz Khalifa": "UCVp3nfGRxmMadNDuVbJSk8A",
    "Dua Lipa": "UC-J-KZfRV8c13fOCkhXdLiQ",
    "Cardi B": "UCxMAbVFmxKUVGAll0WVGpFw",
    "Post Malone": "UCeLHszkByNZtPKcaVXOCOQQ",
    "Pitbull": "UCv8nzwVPQDRjkPCkEsOdEwA",
    "Charlie Puth": "UCwppdrjsBPAZg5_cUwQjfMQ",
    "Calvin Harris": "UCIjYyZxkFucP_W-tmXg_9Ow",
    "YoungBoy Never Broke Again": "UClW4jraMKz6Qj69lJf-tODA",
    "Marshmello": "UCEdvpU2pFRCVqU6yIPyTpMQ",
    "Alan Walker": "UCJrOtniJ0-NWz37R30urifQ",
    "Future": "UCSDvKdIQOwTfcyOimSi9oYA",
    "Sean Paul": "UCkdc7gHpavxpgGalxKbgSHA",
    "The Chainsmokers": "UCq3Ci-h945sbEYXpVlw7rJg",
    "Adele": "UCsRM0YB_dabtEPGPTKo-gcw",
    "Migos": "UC9YcTIQuhwgoOQqYMKYqW9A",
    "Kendrick Lamar": "UC3lBXcrKFnFAFkfVk5WuKcQ",
    "Lil Baby": "UCVS88tG_NYgxF6Udnx2815Q",
    "Shawn Mendes": "UCAvCL8hyXjSUHKEGuUPr1BA",
    "Travis Scott": "UCtxdfwb9wfkoGocVUAJ-Bmg",
    "Sidemen": "UCDogdKl7t7NHzQ95aEwkdMw",
    "One Direction": "UCb2HGwORFBo94DmRx4oLzow",
    "Sam Smith": "UCvpDeGlR5wLP9Z3Tb6K0Xfg",
    "DJ Snake": "UC_x8HoD18XJkILQBreVENUQ",
    "50 Cent": "UC8zJedg1f4sKnyuHWeS6vyw",
    "Usher": "UCaNrhBiXsXIM2epDl_kEzgQ",
    "Snoop Dogg": "UC-OO324clObi3H-U0bP77dw",
    "Young Thug": "UCuwdplPbuTFZj_64d03tSBA",
    "Jennifer Lopez": "UCr8RjWUQ_9KYcIPmWiqBroQ",
    "Doja Cat": "UCzpl23pGTHVYqvKsgY0A-_w",
    "Black Eyed Peas": "UCBFaOy1_APEXEyA6Gws_Y1g",
    "Kanye West": "UCs6eXM7s8Vl5WcECcRHc2qQ",
    "XXXTentacion": "UCM9r1xn6s30OnlJWb-jc3Sw",
    "Halsey": "UCOCgB3xd-B-1qAm-hR9OLrA",
    "Akon": "UC6IBMCQ6-d7p41KHxOsq4RA",
    "Ty Dolla $ign": "UClVY6MdQxTZUaMDL-dLQDcw",
    "Camila Cabello": "UCio_FVgKVgqcHrRiXDpnqbw",
    "Miley Cyrus": "UCn7dB9UMTBDjKtEKBy_XISw",
    "Queen": "UCiMhD4jzUqG-IgPzUmmytRQ",
    "Demi Lovato": "UCZkURf9tDolFOeuw_4RD7XQ",
    "Mariah Carey": "UCurpiDXSkcUbgdMwHNZkrCg",
    "Santana": "UCI7pNDDat9jR8TjgF48aBDA",
    "Avicii": "UCPHjpfnnGklkRBBTd0k6aHg",
    "Britney Spears": "UCgffc95YDBlkGrBAJUHUmXQ",
    "Kevin Gates": "UCj2GTFekdV3EUsTVN8oaEqA",
    "Bebe Rexha": "UC5-gWZXAQqSGVfPHkA7NRiQ",
    "Lana Del Rey": "UCqk3CdGN_j8IR9z4uBbVPSg",
    "Justin Timberlake": "UC-y8ci7xfsu4L3zkSuHae0A",
    "OneRepublic": "UCi4EDAgjULwwNBHOg1aaCig",
    "AC/DC": "UCB0JSO6d5ysH2Mmqz5I9rIw",
    "Guns N' Roses": "UCIak6JLVOjqhStxrL1Lcytw",
    "Meghan Trainor": "UCkXgEcpoTE4tHsebYBouWpA",
    "Lil Durk": "UCaxOQZrF5llUMp-JjesUz1A",
    "Kodak Black": "UChEYVadfkMCfrKUi6qr3I1Q",
    "Anne-Marie": "UCBL7ZxVX4GvW4CFiES_-0YA",
    "Major Lazer": "UCMJ5Qf3sOvQpcYiai1Noa3Q",
    "Ellie Goulding": "UCt-am4x4ZyeohfgM85qFgdQ",
    "21 Savage": "UCOjEHmBKwdS7joWpW0VrXkg",
    "KATSEYE": "UCA61H4fWOMHikLcUFKyQUog",
    "P!nk": "UCE5yTn9ljzSnC_oMp9Jnckg",
    "Khalid": "UCkntT5Je5DDopF70YUsnuEQ",
    "Daft Punk": "UC_kRDKYrUlrbtrSiyu5Tflg",
    "Juice WRLD": "UC0BletW9phE4xHFM44q4qKA",
    "Tyga": "UC-Eh1lR_tWVtv9AvxLybMtQ",
    "De La Ghetto": "UCRp097cJIVS-cQ_GuZWQkJg",
    "Ne-Yo": "UCvtkFm0XlCLqyvtP7UpqAoA",
    "Skrillex": "UC_TVqp_SyG6j5hG-xVRy95A",
    "DaBaby": "UC2CCXzC56k0b8L49R_iW-Yw",
    "Madonna": "UC81VD6eeuLLSfyY_D-N8sVw",
    "Clean Bandit": "UCvhQPdeTHzIRneScV8MIocg",
    "Martin Garrix": "UC5H_KXkPbEsGs0tFt8R35mA",
    "Red Hot Chili Peppers": "UCEuOwB9vSL1oPKGNdONB4ig",
    "6ix9ine": "UCF6jRAgCbSanHolKt0Vt6Qw",
    "Bon Jovi": "UCkBwnm7GOfYHsacwUjriC-w",
    "Gucci Mane": "UCSugZEYrWbzqIWGD195V-YA",
    "Metallica": "UCbulh9WdLtEXiooRcYK7SWw"
}

MAX_VIDEO_PER_CHANNEL = 150
MAX_COMMENTS_PER_VIDEO = 50
TOP_VIDEOS_FOR_COMMENTS = 30
OUTPUT_FILE = 'data/artist_video_data.json'
RAW_DATA_FILE = 'data/raw_video_data.json'

